Jenkinsfile

Using Jenkinsfile instead of job configuration in Jenkins

Jenkins build

---

openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeDBRulesSensor.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeDBSensor.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeDebugListingSensor.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeListingSensor.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeSensor.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeWarningsSensor.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeXREFSensor.java

Sensors updated to new signatures

Upgrade to SQ 5.6

---

proparse/src/main/antlr/JPTreeParser.g
proparse/src/main/antlr/TreeParser01.g
proparse/src/main/antlr/proparse.g
proparse/src/test/resources/data/bugsfixed/bug33.cls

All CREATE xxx now support properties as the target

---

database-parser/src/main/java/eu/rssw/antlr/database/DumpFileVisitor.java

Prevent NPE in case of incr DF

---

proparse/src/main/antlr/TreeParser01.g
proparse/src/main/java/org/prorefactor/core/nodetypes/FieldRefNode.java
proparse/src/main/java/org/prorefactor/treeparser/FieldLookupResult.java
proparse/src/main/java/org/prorefactor/treeparser/ISymbol.java
proparse/src/main/java/org/prorefactor/treeparser/IWidget.java
proparse/src/main/java/org/prorefactor/treeparser/Symbol.java
proparse/src/main/java/org/prorefactor/treeparser/SymbolScope.java
proparse/src/main/java/org/prorefactor/treeparser/Widget.java
proparse/src/main/java/org/prorefactor/widgettypes/Browse.java
proparse/src/main/java/org/prorefactor/widgettypes/Button.java
proparse/src/main/java/org/prorefactor/widgettypes/IFieldLevelWidget.java
proparse/src/main/java/org/prorefactor/widgettypes/Image.java
proparse/src/main/java/org/prorefactor/widgettypes/Rectangle.java

BlockIterator also increments numReads

---

openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/CPDCallback.java
openedge-plugin/src/test/java/org/sonar/plugins/openedge/sensor/OpenEdgeProparseSensorTest.java

Skipped code blocks replaced by a random identifier

---

openedge-checks/src/main/java/org/sonar/plugins/openedge/api/Constants.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/CPDCallback.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/OpenEdgeSettings.java
openedge-plugin/src/test/java/org/sonar/plugins/openedge/sensor/OpenEdgeProparseSensorTest.java
openedge-plugin/src/test/resources/project1/src/classes/rssw/testclass.cls
openedge-plugin/src/test/resources/project1/src/procedures/test3.p

New sonar.oe.cpd.skip_methods and sonar.oe.cpd.skip_procedures properties

---

openedge-checks/src/main/java/org/sonar/plugins/openedge/api/Constants.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/OpenEdgePlugin.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/OpenEdgeSettings.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeXREFSensor.java
openedge-plugin/src/test/java/org/sonar/plugins/openedge/sensor/InvalidXMLFilterStreamTest.java

Implementation of sonar.oe.filter.xref.bytes property

---

proparse/src/main/antlr/JPTreeParser.g
proparse/src/main/antlr/TreeParser01.g
proparse/src/main/antlr/proparse.g

CATCH argument should be ID, not FIELD

---

openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/OpenEdgeSettings.java
proparse/src/main/java/org/prorefactor/core/schema/Schema.java

Aliases set on wrong DB name

---

Jenkinsfile

'mvn install' only on master branch

---

proparse/src/main/antlr/TreeParser01.g
proparse/src/main/java/org/prorefactor/treeparser/Dataset.java
proparse/src/main/java/org/prorefactor/treeparser/Datasource.java
proparse/src/main/java/org/prorefactor/treeparser/Event.java
proparse/src/main/java/org/prorefactor/treeparser/FieldBuffer.java
proparse/src/main/java/org/prorefactor/treeparser/FieldContainer.java
proparse/src/main/java/org/prorefactor/treeparser/ISymbol.java
proparse/src/main/java/org/prorefactor/treeparser/Primative.java
proparse/src/main/java/org/prorefactor/treeparser/Query.java
proparse/src/main/java/org/prorefactor/treeparser/Routine.java
proparse/src/main/java/org/prorefactor/treeparser/Stream.java
proparse/src/main/java/org/prorefactor/treeparser/Symbol.java
proparse/src/main/java/org/prorefactor/treeparser/TableBuffer.java
proparse/src/main/java/org/prorefactor/treeparser/Value.java
proparse/src/main/java/org/prorefactor/treeparser/Variable.java
proparse/src/main/java/org/prorefactor/treeparser/Widget.java
proparse/src/main/java/org/prorefactor/treeparser01/ITreeParserAction.java
proparse/src/main/java/org/prorefactor/treeparser01/TP01Action.java
proparse/src/main/java/org/prorefactor/treeparser01/TP01Support.java
proparse/src/main/java/org/prorefactor/widgettypes/Browse.java
proparse/src/main/java/org/prorefactor/widgettypes/Button.java
proparse/src/main/java/org/prorefactor/widgettypes/Frame.java
proparse/src/main/java/org/prorefactor/widgettypes/Image.java
proparse/src/main/java/org/prorefactor/widgettypes/Menu.java
proparse/src/main/java/org/prorefactor/widgettypes/MenuItem.java
proparse/src/main/java/org/prorefactor/widgettypes/Rectangle.java
proparse/src/main/java/org/prorefactor/widgettypes/Submenu.java

Don't push event parameters on the main symbol scope

---

openedge-checks/src/main/java/org/sonar/plugins/openedge/api/Constants.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/OpenEdgePlugin.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/OpenEdgeSettings.java
proparse/src/main/java/org/prorefactor/proparse/Preprocessor.java
proparse/src/main/java/org/prorefactor/refactor/settings/ProparseSettings.java
proparse/src/test/java/org/prorefactor/core/unittest/OpSysTest.java
proparse/src/test/java/org/prorefactor/core/unittest/util/UnitTestBackslashProparseSettings.java
proparse/src/test/java/org/prorefactor/core/unittest/util/UnitTestProparseSettings.java
proparse/src/test/resources/data/bugsfixed/escape.i
proparse/src/test/resources/data/bugsfixed/escape_char2.p

Issue #72 - Test case

---

proparse/src/main/antlr/JPTreeParser.g
proparse/src/main/antlr/proparse.g
proparse/src/test/java/org/prorefactor/core/unittest/NewSyntaxTest.java
proparse/src/test/resources/data/newsyntax/11n/ParameterHandleTo.p

HANDLE TO can use MEMPTR as datatype

---

listing-parser/src/main/java/eu/rssw/listing/ListingParser.java
listing-parser/src/test/java/eu/rssw/listing/TestListing.java
listing-parser/src/test/resources/listing4.txt
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeListingSensor.java

ListingParser issue with unknown block type on first line

---

openedge-plugin/src/main/java/org/sonar/plugins/openedge/colorizer/OpenEdgeColorizerFormat.java

// comment handling

---

database-parser/src/main/antlr4/eu/rssw/antlr/database/DumpFileGrammar.g4

Change type of a few fields (to NUMBER)

---

openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/CPDCallback.java

Don't generate CPD info for zero-length tokens

---

openedge-plugin/pom.xml
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeProparseSensor.java
pom.xml

Catch RuntimeException when lex'ing include files

---

proparse/src/main/antlr/JPTreeParser.g
proparse/src/main/antlr/TreeParser01.g
proparse/src/main/antlr/proparse.g
proparse/src/test/java/org/prorefactor/core/unittest/BugFixTest.java
proparse/src/test/resources/data/bugsfixed/createComObject.p

CREATE COM-OBJECT grammar issue

---

proparse/src/main/java/org/prorefactor/treeparser/ContextQualifier.java
proparse/src/main/java/org/prorefactor/treeparser/ISymbol.java
proparse/src/main/java/org/prorefactor/treeparser/Symbol.java

Add number of references to variable counts

---

openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/OpenEdgeRulesDefinition.java

Warnings as code smell and not as bug

---

proparse/src/main/antlr/TreeParser01.g
proparse/src/main/antlr/proparse.g
proparse/src/test/resources/data/bugsfixed/nobox.p

In order to see if new ones appear...

Fix all warnings in grammars

---

database-parser/src/main/antlr4/eu/rssw/antlr/database/DumpFileGrammar.g4
database-parser/src/test/resources/sp2k.df

Constraint support in DF files

---

openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeDBRulesSensor.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeDBSensor.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeListingSensor.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeProparseSensor.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeSensor.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeWarningsSensor.java
openedge-plugin/src/test/java/org/sonar/plugins/openedge/sensor/OpenEdgeDBSensorTest.java
openedge-plugin/src/test/java/org/sonar/plugins/openedge/sensor/OpenEdgeListingSensorTest.java
openedge-plugin/src/test/java/org/sonar/plugins/openedge/sensor/OpenEdgeSensorTest.java
openedge-plugin/src/test/java/org/sonar/plugins/openedge/sensor/OpenEdgeWarningsSensorTest.java

Issue #314 (a.k.a. issue π or 🍰)

No sensors on test files, except code colorizer

---

proparse/src/main/antlr/JPTreeParser.g
proparse/src/main/antlr/TreeParser01.g
proparse/src/test/resources/data/bugsfixed/createComObject.p

CREATE statement for automation objects

---

proparse/src/main/antlr/proparse.g
proparse/src/test/java/org/prorefactor/core/unittest/BugFixTest.java
proparse/src/test/resources/data/bugsfixed/double-colon.p

Double colon issue

---

proparse/src/main/antlr/JPTreeParser.g
proparse/src/test/java/org/prorefactor/core/unittest/BugFixTest.java
proparse/src/test/resources/data/bugsfixed/oscreate.p

OS-CREATE-DIR issue

---

openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/OpenEdgeSettings.java

Allow multiple entries in sonar.oe.binaries

---

openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeWarningsSensor.java
openedge-plugin/src/test/java/org/sonar/plugins/openedge/sensor/OpenEdgeWarningsSensorTest.java
openedge-plugin/src/test/java/org/sonar/plugins/openedge/utils/TestProjectSensorContext.java
openedge-plugin/src/test/resources/project1/build/.pct/procedures/test3.p.warnings

Warnings sensor issue

---

openedge-checks/src/main/java/org/sonar/plugins/openedge/api/checks/OpenEdgeProparseCheck.java
proparse/src/main/antlr/proparse.g
proparse/src/main/java/org/prorefactor/core/JPNode.java
proparse/src/main/java/org/prorefactor/proparse/NodeFactory.java
proparse/src/main/java/org/prorefactor/proparse/ParserSupport.java
proparse/src/main/java/org/prorefactor/proparse/antlr4/ProgressLexer.java
proparse/src/test/java/org/prorefactor/core/unittest/ApiTest.java
proparse/src/test/java/org/prorefactor/core/unittest/PreprocessorDirectiveTest.java
proparse/src/test/resources/data/preprocessor/preprocessor05.i
proparse/src/test/resources/data/preprocessor/preprocessor05.p

Proparse directives as hidden tokens, not as AST

---

proparse/src/main/java/org/prorefactor/proparse/antlr4/Lexer.java
proparse/src/test/java/org/prorefactor/core/unittest/PreprocessorVariablesTest.java
proparse/src/test/resources/data/preprocessor/preprocessor06.p

~n handling in preprocessor variable definition

---

database-parser/src/main/antlr4/eu/rssw/antlr/database/DumpFileGrammar.g4
database-parser/src/test/resources/sp2k.df

LOB-SIZE attribute in DF parser

---

proparse/src/test/java/org/prorefactor/core/unittest/BugFixTest.java
proparse/src/test/resources/data/bugsfixed/definemenu.p

Issue #356, just the test case

Issue #356 - Won't fix

---

proparse/src/test/java/org/prorefactor/core/unittest/BugFixTest.java
proparse/src/test/resources/data/bugsfixed/abstractkw.p

ABSTRACT field name

---

proparse/src/main/java/org/prorefactor/treeparser/TreeParserSymbolScope.java
proparse/src/main/java/org/prorefactor/treeparser/symbols/Routine.java
proparse/src/main/java/org/prorefactor/treeparser01/TP01Support.java

Add reference on TableBuffer too

---

proparse/src/main/antlr/JPTreeParser.g
proparse/src/main/antlr/TreeParser01.g
proparse/src/main/antlr/proparse.g
proparse/src/main/java/org/prorefactor/core/NodeTypes.java
proparse/src/test/java/org/prorefactor/core/unittest/BugFixTest.java
proparse/src/test/resources/data/bugsfixed/noargfunc.p
proparse/src/test/resources/projects/sports2000/proparse.schema

No arg funcs can also be field names

---

proparse/src/main/java/org/prorefactor/treeparser01/TP01Support.java
proparse/src/test/java/org/prorefactor/core/unittest/BugFixTest.java
proparse/src/test/resources/data/bugsfixed/varusage.cls

Static member resolution

---

proparse/src/main/java/org/prorefactor/proparse/antlr4/TokenList.java
proparse/src/test/java/org/prorefactor/core/unittest/LexerTest.java
proparse/src/test/resources/data/lexer/tokenlist08.p

NPE in TokenList.class

---

proparse/src/main/antlr/proparse.g
proparse/src/test/resources/data/bugsfixed/double-colon.p

Problem with ::

---

proparse/src/main/antlr/JPTreeParser.g
proparse/src/main/antlr/TreeParser01.g
proparse/src/main/antlr/proparse.g
proparse/src/test/java/org/prorefactor/core/unittest/BugFixTest.java
proparse/src/test/resources/data/bugsfixed/testextent1.cls
proparse/src/test/resources/data/bugsfixed/testextent2.p

EXTENT function issue

---

database-parser/src/main/antlr4/eu/rssw/antlr/database/DumpFileGrammar.g4

LOB-SIZE number format

---

Jenkinsfile
proparse/src/main/antlr/proparse.g
proparse/src/test/java/org/prorefactor/core/unittest/BugFixTest.java
proparse/src/test/resources/data/bugsfixed/bug34.p
proparse/src/test/resources/data/bugsfixed/bug35.p

Proparse infinite loop

---

openedge-checks/src/main/java/org/sonar/plugins/openedge/api/Constants.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/OpenEdgePlugin.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/OpenEdgeSettings.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeProparseSensor.java
openedge-plugin/src/test/java/org/sonar/plugins/openedge/OpenEdgePluginTest.java

sonar.oe.include.suffixes property

---

proparse/src/main/java/org/prorefactor/proparse/antlr4/PreproEval.java
proparse/src/test/java/org/prorefactor/core/unittest/PreprocessorParserTest.java
proparse/src/test/resources/data/preprocessor/preprocessor01.p

PROPATH in preprocessor expression

---

database-parser/src/main/antlr4/eu/rssw/antlr/database/DumpFileGrammar.g4
database-parser/src/main/java/eu/rssw/antlr/database/DumpFileVisitor.java
database-parser/src/test/java/eu/rssw/antlr/database/TestDumpFile.java
database-parser/src/test/resources/sp2k.df

Issue #525 
* PROGRESS is a valid type for table type
* CHANGE TABLE is synonym for UPDATE TABLE
* ADD UNIQUE INDEX is valid
* HELP can be null

DF parser improvements

---

proparse/src/main/antlr/TreeParser01.g
proparse/src/main/java/org/prorefactor/treeparser01/ITreeParserAction.java
proparse/src/main/java/org/prorefactor/treeparser01/TP01Support.java
proparse/src/test/java/org/prorefactor/core/unittest/BugFixTest.java
proparse/src/test/resources/data/bugsfixed/varusage.cls

Add 'UPDATE' note to multiple function calls
Issue #507

Variable usage improvement 

---

proparse/src/main/antlr/proparse.g
proparse/src/main/antlr4/org/prorefactor/proparse/antlr4/Proparse.g4
proparse/src/main/java/org/prorefactor/proparse/antlr4/JPNodeVisitor.java

Empty statement has to be tagged as a statement

---

openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/CPDCallback.java
openedge-plugin/src/test/java/org/sonar/plugins/openedge/foundation/CPDCallbackTest.java
openedge-plugin/src/test/resources/cpd01.p
openedge-plugin/src/test/resources/cpd02.p
openedge-plugin/src/test/resources/cpd03.p
openedge-plugin/src/test/resources/cpd04.p
proparse/src/main/java/org/prorefactor/core/FlatListBuilder.java
proparse/src/main/java/org/prorefactor/core/JPNode.java
proparse/src/main/java/org/prorefactor/core/ProToken.java
proparse/src/main/java/org/prorefactor/proparse/antlr4/InputSource.java
proparse/src/main/java/org/prorefactor/proparse/antlr4/JPNode.java
proparse/src/main/java/org/prorefactor/proparse/antlr4/Lexer.java
proparse/src/main/java/org/prorefactor/proparse/antlr4/ProToken.java
proparse/src/main/java/org/prorefactor/proparse/antlr4/ProgressLexer.java
proparse/src/test/java/org/prorefactor/core/unittest/LexerTest.java
proparse/src/test/resources/data/lexer/lexer11-2.p
proparse/src/test/resources/data/lexer/lexer11-3.p
proparse/src/test/resources/data/lexer/lexer11.p
proparse/src/test/resources/data/lexer/lexer12.p

CPD engine fixes

---

proparse/src/main/java/org/prorefactor/core/nodetypes/FieldRefNode.java

Fix for invalid cast in FieldRefNode

---

proparse/src/main/java/org/prorefactor/core/JPNode.java
proparse/src/test/java/org/prorefactor/core/unittest/LexerTest.java
proparse/src/test/resources/data/lexer/lexer15.p
proparse/src/test/resources/data/tp01tests/test01.expect.p
proparse/src/test/resources/data/tp01tests/test02.expect.txt

Hidden tokens have to be copied when duplicating a ProToken

---

profiler-parser/src/main/java/eu/rssw/antlr/profiler/ProfilerUtils.java

Use secure XML transformer

---

openedge-checks/src/main/java/org/sonar/plugins/openedge/api/Constants.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/OpenEdgeSettings.java

XREF dir as property

---

openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/OpenEdgeSettings.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeCodeColorizer.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeProparseSensor.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeWarningsSensor.java
openedge-plugin/src/test/java/org/sonar/plugins/openedge/foundation/CPDCallbackTest.java

Delayed initialization of OpenEdgeSettings object

---

database-parser/src/main/java/eu/rssw/antlr/database/DumpFileVisitor.java
database-parser/src/test/java/eu/rssw/antlr/database/TestDumpFile.java
database-parser/src/test/resources/ascIndex.df

Fix NPE in database parser

---

proparse/src/main/java/org/prorefactor/refactor/RefactorSession.java

And using Map#put() from multiple threads
Issue #532

Use synchronized Map as parseBuildDirectory is multi-threaded

---

proparse/src/main/java/org/prorefactor/proparse/antlr4/JPNodeVisitor.java
proparse/src/test/java/org/prorefactor/core/unittest/TreeParser03Test.java
proparse/src/test/resources/treeparser03/test11.cls

Parser issue in OUTPUT parameter LIKE table

---

proparse/src/test/java/org/prorefactor/core/unittest/ParserTest.java
proparse/src/test/resources/data/parser/inputfunc.p

INPUT statement test case

---

proparse/src/test/java/org/prorefactor/core/unittest/ParserTest.java
proparse/src/test/resources/data/parser/objindynfunc.cls
proparse/src/test/resources/data/parser/objindynfunc.p

Disabled test case for temporary parser issue

---

proparse/src/main/antlr4/org/prorefactor/proparse/antlr4/Proparse.g4
proparse/src/test/java/org/prorefactor/core/unittest/BugFixTest.java
proparse/src/test/resources/data/bugsfixed/bug44.cls

DYNAMIC-INVOKE proparse issue

---

proparse/src/main/antlr4/org/prorefactor/proparse/antlr4/Proparse.g4
proparse/src/test/java/org/prorefactor/core/unittest/BugFixTest.java
proparse/src/test/resources/data/bugsfixed/bug45.p

DYNAMIC-PROPERTY Proparse issue 

---

proparse/src/main/java/org/prorefactor/proparse/antlr4/TreeParser.java
proparse/src/test/java/org/prorefactor/core/TreeParser03Test.java
proparse/src/test/resources/treeparser03/test15.p
proparse/src/test/resources/treeparser03/test16.cls

Fix invalid parameter declaration with external functions

---

openedge-checks/src/main/java/org/sonar/plugins/openedge/api/Constants.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/OpenEdgePlugin.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/OpenEdgeSettings.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeCPDSensor.java
openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeProparseSensor.java
openedge-plugin/src/test/java/org/sonar/plugins/openedge/OpenEdgePluginTest.java
openedge-plugin/src/test/java/org/sonar/plugins/openedge/sensor/OpenEdgeCPDSensorTest.java
openedge-plugin/src/test/java/org/sonar/plugins/openedge/sensor/OpenEdgeProparseSensorTest.java

Only for cases when the parser can't be executed on the codebase.

Simple CPD implementation

---

openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/InputFileUtils.java
openedge-plugin/src/test/java/org/sonar/plugins/openedge/foundation/InputFileUtilsTest.java

Do not fail with IllegalArgumentException when FS root dir is different from file directory

---

database-parser/src/main/java/eu/rssw/antlr/database/DumpFileVisitor.java
database-parser/src/main/java/eu/rssw/antlr/database/objects/Field.java
database-parser/src/test/java/eu/rssw/antlr/database/TestDumpFile.java

In addition to Label, have a method that sets and gets the Column-Label field attribute from the progress schema

Adding retrieval of Column-Label field property

---

database-parser/src/main/java/eu/rssw/antlr/database/DumpFileVisitor.java
database-parser/src/main/java/eu/rssw/antlr/database/objects/Field.java
database-parser/src/test/java/eu/rssw/antlr/database/TestDumpFile.java

Adding property in Field class to know whether it has MANDATORY attribute.
That allows rules to check that property and raise issues as needed.

Adding property in Field class to know whether it has MANDATORY attr
